### ISSUE TITLE
CTRL-] breaks after switching between files in different directories

### ISSUE THREAD

**Issue by abrace** [lvht/phpcd.vim#110]
Consider two directories, dir1 and dir2, neither of which contains the other. EDIT: dir1 and dir2 are for two different projects, each with its own autoload file.

1. Start vim in dir1 with g:phpcd_auto_restart set to 1.
2. Edit a php file in dir1. CTRL-] works.
3. Edit a second php file in dir2. CTRL-] works.
4. Switch back to the buffer containing the first php file. CTRL-] no longer works.

At this point, if you enter :set filetype=php , CTRL-] starts working again; I assume this is because setting the filetype causes the ftplugin to be reloaded.

Using NVIM v0.2.0

**Comment by Nomad145** [comment]
I'm encountering the same issue in NeoVim 0.2.  `Ctrl-w-]` works fine, but `Ctrl-]` does not jump to the tag under cursor.  If I do `:set filetype=php`, it does not fix the issue.

I appear to have `g:phpcd_auto_restart = 0` by default, but I tried to repeat the steps above with no success.

If there's any way I can further assist with this issue please let me know.

**Comment by abrace** [comment]
I have edited the issue to specify that the files being switched between are in separate projects.

@Nomad145 , I think we have two different problems. `CTRL-]` *does* work for me at first, but stops working after switching between files as described in the issue. Neither `CTRL-W CTRL-]` nor `CTRL-W ]` ever work for me; both just produce a "No tags file" error, which I never get from `CTRL-]`.

**Comment by Nomad145** [comment]
Ah, you are correct.  I'm working in a single directory.  Thanks for pointing that out.
