### ISSUE TITLE
Can I jump to definition without autoload.php?

### ISSUE THREAD

**Issue by amikai** [lvht/phpcd.vim#113]
In my project, i don't have composer, so i don't have autoload.php.
Can i still jump to definition?

Thanks

**Comment by lvht** [comment]
The composer is not a requirement. However, your project must have a autoload function. 

For example, you register a a php file named `/path/to/my_auto.php`. You need create a `.phpcd.vim` in your project and write code like
```viml
let g:phpcd_autoload_path='/path/to/my_auto.php'
```

If your project only load class by require/include, phpcd.vim will not work at all.

Good luck 😄

**Comment by amikai** [comment]
I am not familar with php. After reading some post about autoload in php, I understand what you mean.
And jump tag in vim is work, Thank you.
