### ISSUE TITLE
Consider not mapping the "K" key by default

### ISSUE THREAD

**Issue by manuel-colmenero** [lvht/phpcd.vim#115]
Hey there, first and foremost, thanks for your effort.

I would suggest you don't map the <kbd>K</kbd> key, here is the line where this happens:
https://github.com/lvht/phpcd.vim/blob/fbb9de484c4142a65f96c9ec3cb6be58b91a199a/ftplugin/php_phpcd.vim#L10-L11

The problem is, this key is used by default in Vim for looking up manual pages, and it can be used for looking up PHP manual pages too, which I recommend:
https://bjori.blogspot.de/2010/01/unix-manual-pages-for-php-functions.html

So maybe don't map <kbd>K</kbd> it by default, or map it by default and let users disable it with an option?

Thanks,
Manu

**Comment by lvht** [comment]
fixed at https://github.com/lvht/phpcd.vim/commit/5da5805114fd6ef150f7e1c0c6f68c57bd7b461f

**Comment by manuel-colmenero** [comment]
That was quick, thanks!
