### ISSUE TITLE
Preview pane doesn't close

### ISSUE THREAD

**Issue by khamer** [lvht/phpcd.vim#118]
Using the most recent version of phpcd with neoplete.vim on vim8. The preview pane shows up and updates correctly, but doesn't close when I select a completion. I'm willing to debug this further, just not sure what'd be the most helpful info to provide.

**Comment by khamer** [comment]
Adding `autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif` fixes this, but I wouldn't have thought that this would be necessary given the gif and docs.

**Comment by lvht** [comment]
fixed at https://github.com/lvht/phpcd.vim/commit/89bdf90fef41980d9c279e17cc91a75bc1a47a79
