### ISSUE TITLE
PHP Parse Errors on $this

### ISSUE THREAD

**Issue by Sydney-o9** [lvht/phpcd.vim#121]
It looks like PHP Parse errors are being triggered on autocomplete on `$this`.

```
PHP Parse error:  syntax error, unexpected '}', expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in ..TestController.php on line 14
Parse error: syntax error, unexpected '}', expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in ..TestController.php on line 14
```
---

All other autocompletes work except autocompletes on `$this->`, here is an example:

```
 10 class TestController extends Controller
 11 {
 12
 13     public function whateverAction() {
 14         return $this->
 15     }
 16
 17 }
```

![image](https://user-images.githubusercontent.com/1480617/33427643-1ee23680-d61a-11e7-84f8-071f7a967b0e.png)

- PHP 5.6.30
- Neovim NVIM v0.2.3-64-g2d732a11b with deoplete

**Comment by lvht** [comment]
Every time you save changes to disk, you must make sure the file saved to the disk is a valid php file.

So if you type `return $this->`, and save it to the disk, phpcd will not work, because the line `return $this->` is invalid.

**Comment by Sydney-o9** [comment]
Thank you - I use `autosave`..
