### ISSUE TITLE
Jump to definition

### ISSUE THREAD

**Issue by Sydney-o9** [lvht/phpcd.vim#122]
I am using `deoplete` and exuberant ctags, when using `phpcd`..

> `ctrl+]` to go to the definition

.. this functionality is lost.

When removing the plugin, <kbd>Ctrl</kbd> <kbd>]</kbd> works again. 

Any ideas why we loose the jump to definition functionality with phpcd?

- PHP `5.6.30`
- Neovim `NVIM v0.2.3-64-g2d732a11b` with `deoplete`

----

## A bit more info

Here is what I've noticed when the plugin is enabled.

<kbd>ctrl</kbd> <kbd>]</kbd> on `Request` doesn't work:
```
use Symfony\Component\HttpFoundation\Request;
```

But <kbd>ctrl</kbd> <kbd>]</kbd> on `BaseRequest` works:
```
use Symfony\Component\HttpFoundation\Request as BaseRequest;
```

**Comment by lvht** [comment]
I use phpcd.vim + php7, and does not recur you problem. I recommend you migrate from php5 to php7.

Even though phpcd.vim support php5, but active development against php5 have finished.

**Comment by lvht** [comment]
By the way, if you use phpcd.vim, the ctags can be dropped. phpcd.vim is designed to replace the ctags.

**Comment by Sydney-o9** [comment]
I understand you use php7, do you use `deoplete` too?

**Comment by lvht** [comment]
Yes, I use `deoplete`. However, the `deoplete` has no business about **Jump to definition**.

**Comment by lvht** [comment]
the `deoplete` is only for **completion**

**Comment by Sydney-o9** [comment]
@lvht  you were right php7 did the trick.. 

It works on this for example

```
class MyController extends Controller
``` 

However, it does not work for other things, like on use statements 

```
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
````

or on `new` statements

```
return new Response(null, Response::HTTP_NO_CONTENT);
```

**Comment by lvht** [comment]
Hi @Sydney-o9 , sorry for misleading. I find this issue too. I will debug it later.
