### ISSUE TITLE
url 404 for php-vim/phpcd.vim

### ISSUE THREAD

**Issue by wsdjeg** [lvht/phpcd.vim#123]
@lvht hi, the old org has been deleted? so the main url of this plugin is `lvht/phpcd.vim`?  and I just found a vim-php, is that for people who use vim when program php?

**Comment by lvht** [comment]
php-vim has been deleted. please use lvht/phpcd.vim. Thank you.

**Comment by wsdjeg** [comment]
ok, got it.
