### ISSUE TITLE
Infinite loop when create a buffer for a new file in a directory .

### ISSUE THREAD

**Issue by kiooss** [lvht/phpcd.vim#126]
Hello lvht,
 
If you create a buffer for a new file in a directory that doesn’t exist, the `phpcd#GetRoot()` function will fall into an infinite loop.

For example, in the project root(with no .phpcd.vim), if I do `vi foo/test.php` (dir `foo` does not exist) and `expand("%:p:h")` seems to return `foo`.

Kind regards.

**Comment by lvht** [comment]
Maybe it's neovim's bug. Just edit `nopath/foo.txt` will block nvim.

**Comment by kiooss** [comment]
Sorry, but it also happened with vim8, and not a vim8/neovim bug I think. The reason is `expand("%:p:h") ` can not get the absolute path for a new buffer in a non existed directory. This will cause an infinite loop in your `phpcd#GetRoot()` function.

**Comment by lvht** [comment]
Just `nvim --noplugin a/b/c.txt` will block.

**Comment by lvht** [comment]
But `vim --noplugin a/b/c.txt` will not block.

**Comment by kiooss** [comment]
And `nvim --noplugin a/b/c.txt` does not block in my machine.

**Comment by lvht** [comment]
I use the **NVIM v0.2.2**. Which version you use?

**Comment by kiooss** [comment]
Check the code below, if I don't have `.phpcd.vim` in my project root, then the first while loop will be an infinite loop.

```
function! phpcd#GetRoot() " {{{
	let pwd = expand("%:p:h")
	let root = pwd

	if g:phpcd_root != '/' && stridx(root, g:phpcd_root) == 0
		return g:phpcd_root
	endif

	while root != "/"
		if (filereadable(root.'/.phpcd.vim'))
			return root
		endif
		let root = fnamemodify(root, ":h")
	endwhile

	let root = pwd
	while root != "/"
		if (filereadable(root . "/vendor/autoload.php"))
			return root
		endif
		let root = fnamemodify(root, ":h")
	endwhile

	return root
endfunction " }}}
```

**Comment by kiooss** [comment]
With `vim --noplugin a/b/c.txt `, what did you get for `:echo expand("%:p:h")`, I got `a/b`.

**Comment by lvht** [comment]
please try https://github.com/lvht/phpcd.vim/commit/626eea54543cb0c72517bc149b05b8aa1e2f2e1c

thank you 👍

**Comment by kiooss** [comment]
The infinite loop is fixed, but the fix has side effect. Now the second loop will not run and GetRoot just return `/` even I have `/vendor/autoload.php` in my project root.

**Comment by lvht** [comment]
The current fix seems enough and simple. Please do create you dir before create new php file.

When you trigger autocomplete or jump, phpcd will get the real path of your current php file, and fetch some information like namespace, use imports and class name. If you trying create a php in a non-exists dir, even phpcd can load the `vendor/autoload.php`, it will not work.

**Comment by lvht** [comment]
Are you chinese?

**Comment by lvht** [comment]
Feel free to make you own fork and changes. PRs are always welcomed.

Thank you.

**Comment by kiooss** [comment]
I usually start vim in my project root. So maybe use `getcwd()` instead of just `/` would be better.
And with my vim config, if I do `vim a/b/c.php` the new dir is created at `BufWrite` point with autocmd.  

```
  if pwd[0] != '/' " for editing non exists dir file
-   let pwd = '/'
+   let pwd = getcwd()
  endif
```

Yes, I'm Chinese.

**Comment by kiooss** [comment]
OK, I'll make a PR, please wait.
