### ISSUE TITLE
Use Laravel IDE Helper with phpcd.vim

### ISSUE THREAD

**Issue by maamo888** [lvht/phpcd.vim#135]
Hi.

Thank you for a useful phpcd.vim.

Do you know the Laravel IDE Helper?
https://github.com/barryvdh/laravel-ide-helper

Please tell me how to use Laravel IDE Helper with phpcd.vim.

Make a `_ide_helper.php` with called `php artisan ide-helper:generate` command.

Is there a way to use `_ide_helper.php` with phpcd.vim?
e.g: https://github.com/lvht/phpcd.vim/wiki/Laravel-Facade-Support

**Comment by lvht** [comment]
create a php named after '.autoload.php'

```php
<?php
require './vendor/autoload.php';
require './_ide_helper.php';
```

and create the `.phpcd.vim` and put
```viml
let g:phpcd_autoload_path = '.autoload.php'
```

**Comment by lvht** [comment]
@maamo888 The [wiki](https://github.com/lvht/phpcd.vim/wiki/Laravel-Facade-Support) has been updated as well.

**Comment by maamo888** [comment]
Thanks!!

**Comment by maamo888** [comment]
Files containing namespace can not be supplemented.

## OK

<img width="704" alt="ok" src="https://user-images.githubusercontent.com/14961986/37017680-d2b8a20e-2154-11e8-92cd-6c7f14a9cf9c.png">

## NG (namespace)

<img width="512" alt="ng_namespace" src="https://user-images.githubusercontent.com/14961986/37017692-daf1b1f4-2154-11e8-8c55-c99f1af0c3f5.png">

**Comment by lvht** [comment]
The DB id defined in to global namespace. If your file has a namespace, you should use `\DB` instead of `DB`. Please full fill your basic PHP knowledge before fire any issue.

**Comment by maamo888** [comment]
Thanks!!!!
