### ISSUE TITLE
Static method completion of [User] class becomes wrong state.

### ISSUE THREAD

**Issue by maamo888** [lvht/phpcd.vim#138]
A completion list is output in this way even though the `User` class is not defined.

Even if you actually define the `User` class, it will not be referenced.

Is it judged like `use` syntax?

Please, need some assistance

**OS & Vim**

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 15 2018 06:44:07)
macOS version
Included patches: 1-1608
```

**PHP**

```
PHP 7.2.2 (cli) (built: Feb 26 2018 10:33:13) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.2, Copyright (c) 1999-2018, by Zend Technologies
```

### Simple Case

**tree**

```
phpcdissue$ tree
.
└── sample.php

0 directories, 1 file
```

**sample.php**

![sample php](https://user-images.githubusercontent.com/14961986/37509027-f14db574-2938-11e8-80fc-617456c91eb8.png)

### Laravel

![laravel php](https://user-images.githubusercontent.com/14961986/37509039-fabeb086-2938-11e8-8b1c-84fe7ed9462c.png)

**Comment by maamo888** [comment]
here?

https://github.com/lvht/phpcd.vim/blob/master/autoload/phpcd.vim#L59

**Comment by lvht** [comment]
It is a bug. Would you @maamo888 like to make a PR?

**Comment by maamo888** [comment]
Sorry, I can not do PR because Vim script is not good at it.

**Comment by maamo888** [comment]
```vimrc
		if context =~# '\v^use\s*' " {{{
```
