### ISSUE TITLE
$this can not completion assertXXX of PHPUnit

### ISSUE THREAD

**Issue by maamo888** [lvht/phpcd.vim#140]
Ref: http://phpunit.readthedocs.io/en/latest/writing-tests-for-phpunit.html

Example: `$this->assertSame`.

`self::` is of course OK.

## [NG]Completion

<img width="500" alt="1_assert" src="https://user-images.githubusercontent.com/14961986/37628831-b15afbb4-2c1e-11e8-8833-31a972082e4b.png">

## [OK]Jump

`:call phpcd#JumpToDefinition('split')`

<img width="500" alt="2_jump" src="https://user-images.githubusercontent.com/14961986/37628844-c2d4ffe8-2c1e-11e8-90d2-996333268ca6.png">

## [OK]PhpStorm

<img width="500" alt="3_phpstorm_assert" src="https://user-images.githubusercontent.com/14961986/37628856-cdd72948-2c1e-11e8-9ce0-55efb744c16e.png">

**Comment by maamo888** [comment]
I could completion my `.vimrc` by `setting phpcd_disable_static_filter = 1`

```vim
let g:phpcd_disable_static_filter = 1
```

<img width="500" alt="4_ok_phpcd_disable_static_filter" src="https://user-images.githubusercontent.com/14961986/37634057-3aaca94e-2c38-11e8-8081-a4ae22b2df05.png">

`is_static = 'both'` seems to be complemented by being judged.

What's the intention of setting this `phpcd_disable_static_filter`?

Is the default value of plugin's `phpcd_disable_static_filter` better `1`?

**Comment by lvht** [comment]
If you type `$this->`, phpcd will only list none static methods and variables. If you type `self::`, phpcd will only list static methods and variables.

If you use the Laravel framework, you will use facades like `DB`, `Auth`. This facades has magic method `__call` like this

```php
<?php
function __call($name, $args) {
     $instance =  new self;
     return call_user_function_array([$instance, $name], $args);
}
```

This facades does not has these **static methods**, but you can use the `::` to call them. So I introduce the phpcd_disable_static_filter to change the default behavior.

**Comment by maamo888** [comment]
Thank you for reply!

This issue is independent of `Laravel` issue, it is a `simple PHPUnit` issue.

PHPUnitでは慣習的にAで静的メソッドを呼び出すので気になりました。

PHPUnit customarily calls static methods on `$this->`, so I was concerned.

see: http://phpunit.readthedocs.io/en/latest/assertions.html

**Comment by lvht** [comment]
Use `self::` instead of `$this->` or set the `phpcd_disable_static_filter`

**Comment by yaegassy** [comment]
I hope `phpcd.vim` will be the most useful Vim plugin for PHP.

Thanks close.

**Comment by maamo888** [comment]
I hope `phpcd.vim` will be the most useful Vim plugin for PHP.

Thanks.

**Comment by lvht** [comment]
Use `20%` code to solve `80%` problem. But the last `20%` problem will be fixed by additional `80%` code.

**Comment by lvht** [comment]
phpcd.vim is just a small, lightweight util for php developer who are familiar with vim. phpcd.vim is not designed to solve all problem but make it possible to extend vim by php.

**Comment by lvht** [comment]
@maamo888 Maybe you would like the https://github.com/lvht/phpfold.vim

**Comment by maamo888** [comment]
@lvht Thank you, I will try it.

**Comment by maamo888** [comment]
Thanks. vim-plug (`do`).

```
Plug 'lvht/phpfold.vim', { 'for': 'php', 'do': 'composer install' }
```

Good fold.

**Comment by lvht** [comment]
The key point of phpfold.vim is that it use php parser to detect how to fold. PHP programer can change it easily.
