### ISSUE TITLE
Exception on completions in non-package scripts

### ISSUE THREAD

**Issue by tweekmonster** [lvht/phpcd.vim#141]
The following generates an exception:

```php
/**
 * @param \Exception $e
 */
function handle_exception($e)
{
  $e->
}
```

But this works fine:

```php
/**
 * @param \Exception $e
 */
function handle_exception($e)
{
  /** @var \Exception $e */
  $e->
}

```

Exception:

```
Fatal error: Uncaught ErrorException: Uninitialized string offset: 0 in /home/tallen/.config/nvim/plugins/phpcd.vim/vendor/composer/ClassLoader.php:317
Stack trace:
#0 /home/tallen/.config/nvim/plugins/phpcd.vim/vendor/composer/ClassLoader.php(317): {closure}(8, 'Uninitialized s...', '/home/tallen/.c...', 317, Array)
#1 /home/tallen/.config/nvim/plugins/phpcd.vim/vendor/composer/ClassLoader.php(300): Composer\Autoload\ClassLoader->findFile('')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('')
#3 [internal function]: spl_autoload_call('')
#4 /home/tallen/.config/nvim/plugins/phpcd.vim/php/PHPCD.php(411): ReflectionClass->__construct('\\')
#5 /home/tallen/.config/nvim/plugins/phpcd.vim/php/PHPCD.php(398): PHPCD\PHPCD->argTypeByHint('\\', 'handle_exceptio...', 'e', '/home/tallen/de...')
#6 [internal function]: PHPCD\PHPCD->argtype('\\', 'handle_exceptio...', 'e', '/home/tallen/de...')
#7 /home/tallen/.config/nvim/plugins/phpcd.vim/vendor/lvht/msgpack-rpc/src/AbstractServer.php(88): call_user_func_array(Arr in /home/tallen/.config/nvim/plugins/phpcd.vim/vendor/composer/ClassLoader.php on line 317
```

Removing this line stops the exception, but still gives no completions: https://github.com/lvht/phpcd.vim/blob/master/php/PHPCD.php#L351

**Comment by lvht** [comment]
This issue has been fiexed. However, you cannot complete in this case because phpcd.vim has been refactored and only get function's information by reflection. But php does not support autoload function so php will not see `handle_exception`'s doc block if it not loaded before.

**Comment by tweekmonster** [comment]
> This issue has been fiexed.

I just updated and I'm still getting the exception.

> However, you cannot complete in this case because phpcd.vim has been refactored and only get function's information by reflection.

That's pretty frustrating since it was working before.  I understand the desire for high accuracy, but the simplest solution here is to scan backwards for doc blocks that match the completion scope as a fallback.  I would prefer _any completion hint_, even if it's low-tech, if the alternative is _nothing_.

> But php does not support autoload function so php will not see handle_exception's doc block if it not loaded before.

This isn't an autoload issue.  The file path is known since function is within the file being edited.  Additionally, the completion wasn't for the function, it was for an argument using a built-in class.  As I mentioned, it **actually works** if I use `/** @var ... */`, so it should at the very least be able to read the function's params.

Regardless, it shouldn't generate an exception and interrupt what I'm doing.  That's literally a bug.

**Comment by lvht** [comment]
@tweekmonster please see [this commit](https://github.com/lvht/phpcd.vim/commit/bf378e3ffccb5b12cc689e75efbd4d567faf8e25).

phpcd.vim will never support all features. We want to use the 20% code to solve the 80% feature. All other feature should be implemented by the user.

**Comment by tweekmonster** [comment]
@lvht Please see this video for why I believe that this needs to be fixed: https://share.esdf.io/GwHjW97v5j/Screen-Recording-2018-04-03-00-39-13.mp4

That is a bug and it's very disruptive.

> We want to use the 20% code to solve the 80% feature. All other feature should be implemented by the user.

I'm not someone that expects this plugin to provide all PHP features and turn vim into an IDE.  I worked on completion plugins, too.  I've contributed a large chunk of code to deoplete-jedi and have made the same argument for not supporting everything in Python.  I use ctags to deal with functional completions because I **completely understand** the issue with no function autoloading.  But, I believe this plugin should still be able to resolve what `\Exception` or `\package\Class` is regardless of where the editing file is on disk.

All I ask is if there is no match using reflection, go low tech and scan upwards for comments like it used to.  If it finds a resolvable class, then show completions for that.  If you refuse to do it, at least make some sort of API hook/callback for me to write a fallback method for finding the namespace/class and triggering the completion menu.  I'm willing to do it, but I don't want to create an entire plugin to duplicate 80% of your code.  Since you removed the old code that did it, I believe you'd refuse a PR that basically restored it as a fallback method.

Even if you refuse to do anything I just requested, could you please at least **handle the exception!!!!!**

**Comment by tweekmonster** [comment]
Never mind.  I found a plugin that works better.

**Comment by lvht** [comment]
enjoy yourself

**Comment by tweekmonster** [comment]
I will.  I still hope that you will handle/suppress the exception.  If you don't, you're no longer standing on principal--you're just being stubborn because the context of my work doesn't exactly fit your preferred project style.

Also, the 80/20 rule is naive in practice.  It's good material for management speeches. 
It's in regard to resolving [80% of the bugs by fixing 20% of the code](https://en.wikipedia.org/wiki/Pareto_principle#In_software).  Your refactor introduced a bug and reduced feature coverage.

**Comment by lvht** [comment]
Hello @tweekmonster. I introduce the [BetterReflection](https://github.com/Roave/BetterReflection) to __reflect__ information of current php source without autoload enabled. 

It fixed your issue and you can see the changes at https://github.com/lvht/phpcd.vim/compare/0fac411752768388c4296066c020054439648a97...lvht:master.

phpcd is not the best but the cheapest.

---
> Never mind. I found a plugin that works better.

By the way, would you like offer the name of your better plugin?
