### ISSUE TITLE
Fetching property type from construct

### ISSUE THREAD

**Issue by Isty001** [lvht/phpcd.vim#142]
This is rather a feature request, but it'd be awesome to have, so no unnecessary doc would be needed.

Let's consider the following example:

```php
class A 
{
    public function something() {}
}

class B
{
    private $a;

    public function __construct(A $a)
    {
        $this->a = $a;
    }

    public function test()
    {
        $this->a->something();
    }
}
```
In `B::test` the `$this->a` methods, and properties won't be completed, because there is no phpdoc for the property. Is it possible to implement it? If you could give some guide how, I'll look at the code and try to help with it. 

Thanks!

**Comment by lvht** [comment]
Hello @Isty001 , it is a little completed.

We could use reflection to get the `__construct` method's parameters type and start line and end line. Then we could get the body of the `__construct`. We can then use the php-parser to parser the body and find all the assignment and detect the assigned type.

This is a huge improvement feature.

**Comment by Isty001** [comment]
Yes, this is what I roughly thought about, and I know it's probably not an easy task. :-)  Any chance that you would implement it in the future?

I already checked the code, but unfortunately the structure of the plugin is not completely clear yet. If you could give me a hand, where this stuff need to be processed (I assume somewhere in `PHPCD::classInfo`), I'll try to take a look at it and see what can I do.

**Comment by lvht** [comment]
I made a prototype ad https://github.com/lvht/phpcd.vim/commit/e38fb57489d9ccd3d76a2e237a78fff48147514e

FYI @Isty001

**Comment by Isty001** [comment]
Thank you very much! I just made a quick check, and it looks fantastic!
You are awesome! :smile:

**Comment by Isty001** [comment]
Thank you very much!

**Comment by lvht** [comment]
updated
