### ISSUE TITLE
Symfony autocompletion

### ISSUE THREAD

**Issue by alexdrupal** [lvht/phpcd.vim#143]
Hello

Any plan to support Symfony2-3 projects. Like in this project (it seems abandoned): https://github.com/m2mdas/phpcomplete-extended-symfony

Thank you : -)

**Comment by lvht** [comment]
phpcd is a php process and use reflection to fetch the information for completion and jump. You can use phpcd for any project only if it has a autoloader. The default autoloader is the loader generated by composer.

I don't use symfony. But if symfony has a autoloader, it should be supported.

**Comment by lvht** [comment]
[Here](https://github.com/lvht/phpcd.vim/wiki/Laravel-Facade-Support) is how to make phpcd support laravel facade. FYI.

**Comment by alexdrupal** [comment]
Thanks. I will take a look at the Laravel plugin.
