### ISSUE TITLE
How can I work around GoToDefinition not working due to PHP deprecated errors in my code?

### ISSUE THREAD

**Issue by kidonchu** [lvht/phpcd.vim#144]
The plugin works great most of the time and I really like it. However, some of code bases I work with are really old and have bunch of legacy code from php4. When I work with these codes, I can't get GoToDefinition to work because of deprecation warnings.
```
Error detected while processing function phpcd#JumpToDefinition[10]..phpcd#LocateSymbol[10]..rpc#request:
line    3:
"Uncaught ErrorException: Methods with the same name as their class will not be constructors in a future version of PHP; Class_Name has a deprecated constructor in /dev/classes/smarty.php:16
```
After this error message, it doesn't go to the definition of the function.

Is there any way I can suppress these deprecation warnings (or any warnings) so that I can use GoTo feature in rather old code bases too?

I've tried modifying `php.ini` of my command line `php` by changing `display_errors=Off` but it didn't seem to work.

I'm using this plugin in
- MacOS 10.13.3
- NeoVim 0.2.2

**Comment by lvht** [comment]
I have never used the php4 before. I have no ability to support php4. But I can describe how phpcd.vim work.

phpcd.vim has two parts. One part is written by VimL and the other is PHP. When you open a php file, phpcd.vim will start a php process calll phpcd.php.

When you want to jump into the definition, the VimL part fetch the context information and transfer them to phpcd.php. The phpcd.php then use `ReflectionClass`/`ReflectionMethod` to fetch the file location and tell vim to open the source file. If we cannot reflect a object/method, phpcd can not fetch information about them, so no jump and no complete.

In your situation, the feature that use the same class name as construct name has been dropped in php 5. So you got an `ErrorException` and phpcd cannot reflect the class and no jump.

There is no easy way to fix this issue. Perhaps the most easy way is to refactor the legacy code. And phpcd.vim will never add code to support such legacy code base. Sorry.
