### ISSUE TITLE
Classname completion does not work with lazy-autoloaders?

### ISSUE THREAD

**Issue by trlt** [lvht/phpcd.vim#150]
Classname completion does not work with one of my projects.
As far as I can see, the reason is the way phpcd is investigating the classnames.
[https://github.com/lvht/phpcd.vim/blob/940671a8a08facd758a13b15357f8a414ba25636/php/PHPCD.php#L773](url)

I'm using a lazy autoloader for my project and therefore the class is unknown until it is loaded the first time by phpcd.

Is there a way to get classname completion work with a lazy autoloader?

Otherwise I'm thinking of extending the indexer to build a classname index and using this index for the classname completion.

**Comment by lvht** [comment]
@trlt sorry for late response. Three years late is too late. Because I switched to go programming in 2018, and has no free time to maintain this project. Sorry, again.

The simplest way is switch to use composer as the lazy autoloader. And composer support dump classname index.
