### ISSUE TITLE
how to run php deamon?

### ISSUE THREAD

**Issue by junk123321** [lvht/phpcd.vim#151]
I will pretty newbie to VIM plugins, can you please guide how to run php deamon? When pressing ctrl+x & ctrl+o to complete code, error message shows:
Error detected while processing function phpcd#CompletePHP[59]..phpcd#GetCurrentNameSpace[1]..rpc#request:
line    8:
Invalid channel: 1

I guess it is due to php deamon not run. I just run nvim . in a php project folder.

**Comment by lvht** [comment]
Please read the README.md first.

And maybe you could see some log in the `~/.phpcd.log`.
