### ISSUE TITLE
Error detected while processing function phpcd#JumpToDefinition[10]..phpcd#LocateSymbol[10]..rpc#request:

### ISSUE THREAD

**Issue by yb3616** [lvht/phpcd.vim#154]
Hi there, I got trouble on my thinkphp5.1 project.

error logs on vim(no such file ~/.phpcd.log):
```
PHP Fatal error:  Class 'think\Validate' not found in application/wechat/validate/Authentication.php on line 14
Error detected while processing function phpcd#JumpToDefinition[10]..phpcd#LocateSymbol[10]..rpc#request:
line    8:
"Class 'think\Validate' not found at /srv/http/tp51.ml/www/application/wechat/validate/Authentication.php:14"
Error detected while processing function phpcd#JumpToDefinition[10]..phpcd#LocateSymbol:
line   10:
E714: List required
line   11:
E121: Undefined variable: path
E15: Invalid expression: [path, line, 0]
Error detected while processing function phpcd#JumpToDefinition:
line   10:
E714: List required
line   11:
E121: Undefined variable: symbol_file
E15: Invalid expression: symbol_file == '' || symbol_file == v:false
line   30:
E121: Undefined variable: symbol_line
E116: Invalid arguments for function str2nr
E15: Invalid expression: str2nr(symbol_line) > 0
```

For now, I found it when i ```C+]``` the function defined in ```\think\Model``` or ```\think\Validate```, i will got the fatal message like above. But phpcd do nothing when i ```C+]``` the function like ```cache```, ```session```.

i have done everything that ```phpcd``` required, and i found it can goto definition in one php file without composer file.

By the way, i can do these by using the plug ```mkusher/padawan``` and ```ctags -R```

**Comment by lvht** [comment]
please make sure your phpcd can load the the `\think\Validate` class. Here is the doc from README.md

![image](https://user-images.githubusercontent.com/2030591/43396013-bec2cd1e-9432-11e8-9a15-07cad45e7a2c.png)

**Comment by yb3616** [comment]
你好，我试过在我的项目根目录下面新建```.phpcd.vim``` ，按照你的readme写入```autoload.php```相对路径，还是没有用

**Comment by lvht** [comment]
最简单的办法验证就是写一个 foo.php，require 你的 authoload.php，然后 new think\Validate，看有没有报错。

**Comment by lvht** [comment]
@yb3616 你提供一下 im 联系方式

**Comment by yb3616** [comment]
qq:285554318
