### ISSUE TITLE
Jump to definition failure

### ISSUE THREAD

**Issue by gotoin** [lvht/phpcd.vim#155]
The modified file was not saved，jump to definition failure

**Comment by lvht** [comment]
yes! phpcd use php reflection to find the location of definition.

**Comment by gotoin** [comment]
@lvht 但我要跳转的是未修改之前就已经存在的代码，这也不能跳转吗？

**Comment by gotoin** [comment]
@lvht 但我这目前的测试来看的话，是不行的，我一但对文件做出修改(语法没有错误)未保存的情况下，当前文件都无法跳转了,  您有空的时候可以试试吗？谢谢

**Comment by lvht** [comment]
你可以自己研究一下。phpcd 鼓励自主可控的扩展性。如果你搞不定或不愿意搞，请使用其他工具。

**Comment by gotoin** [comment]
@lvht 好的 谢谢
