### ISSUE TITLE
Completion for implements always resolves to class name

### ISSUE THREAD

**Issue by shadowhand** [lvht/phpcd.vim#157]
```php
use Acme\BarInterface;

class Foo implements Bar<tab>
```

This will always change `Bar` to `Foo`, even though the line already contains `class Foo`.

**Comment by lvht** [comment]
@shadowhand This is more a vim's issue than phpcd's. You could add the following line to your vimr
```
set completeopt=menuone,noinsert,noselect
```

However, phpcd seems not return the real interface list. I will make some debugging.
