### ISSUE TITLE
如何补全包含名字空间的类名

### ISSUE THREAD

**Issue by imnicy** [lvht/phpcd.vim#158]
在输入use Request时，我希望 :Illuminate\Http\Request这个类名字会被提示出来，我应该怎么做。

**Comment by lvht** [comment]
你运行 composer dump-autoload -o 后重启 vim 试试

**Comment by imnicy** [comment]
非常感谢，这样确实可以解决我目前的问题，但是我要输入的可能会多一点，比如我输入use Illuminate\Http\之后才会出现我想要的Illuminate\Http\Request。
但是如果有新增class之后需要重复执行composer dump-autoload -o,稍微会有点麻烦，phpcd.vim在以后的更新中会将通过psr来寻找类名的功能加入吗。

**Comment by lvht** [comment]
phpcd.vim 面向工具流，我们不紧用工具，而且要改造工具，使其更加得心应手。如果你不想研究它，就不要用它。
