### ISSUE TITLE
ImportError: No module named nvim

### ISSUE THREAD

**Issue by zhoupro** [lvht/phpcd.vim#159]
from neovim.api.nvim import NvimError
can't find nvim module, So I comment the line and remove it's usage.
my system is ubuntu18.04. Please check the problem.

**Comment by lvht** [comment]
please seed the README.md.

For neovim, you need install neovim package for python.

**Comment by zhoupro** [comment]
I have installed neovim using pip and pip3, the python package just can find neovim.api, can't find neovim.api.nvim. somthings goes wrong. I look inside the neovim package, it use pyvim instead. But at this moment, it doesn't working.

**Comment by msva** [comment]
@lvht neovim upstream has renamed the client python module. Now it calls `pynvim`.

**Comment by lvht** [comment]
and does your @msva phpcd work?

**Comment by zhoupro** [comment]
comment   #from neovim.api.nvim import NvimError
change   'except  NvimError :' to 'except :' 
after that, I works.
