### ISSUE TITLE
Analyzing divided into two parts

### ISSUE THREAD

**Issue by przepompownia** [lvht/phpcd.vim#16]
At present, some responsibilities for analyzing (e.g. recognizing context) takes place on the vim side and the other on PHPCD. What do you think about this partition? 

For example, what idea on completion of available local variables in given context (like from get_defined_vars() in running code) do you have? Do you want to burden vim side to achieve it? 

/*\* YCM's identifier based completion is not context sensitive and, even worse, does not distinguish between variable and another string. I have disabled it because of showing lots of unneeded items. **/

**Comment by lvht** [comment]
Actually the phpcomplete.vim has some feature like this. However, it's not as better as YCM does, so I droped them at c24c0a09210cb345bcf1b7ce35bab03d9952a64d . FYI.

**Comment by lvht** [comment]
The idea that using get_defined_vars() to make context sensitive completion is amazing, but it seems not easy to implement.

**Comment by przepompownia** [comment]
I mentioned about `get_defined_vars()` only for comparison, not for using, because it this would probably imply code evaluation, which is very insecure.

**Comment by przepompownia** [comment]
Transfer the whole parsing logic to the `PHPCD` side seems to be revolutionary idea that require a lot of work, but it seems to be more clear. For comparison, `eclim` client sends to server the file name and byte offset of cursor (something about `line2byte('.')+col('.')-2`)

     [-editor, vim, -command, php_complete, -p, phpcdFixtures, -f, PHPCD/A/Alpha.php, -o, 503, -e, utf-8]

**Comment by Xerkus** [comment]
byte offset won't work on unsaved buffer

**Comment by przepompownia** [comment]
...unless there is a way to use unsaved buffers to pretend their physical equivalents.

**Comment by Xerkus** [comment]
BetterReflection can parse code passed as string, i wonder if it can be used for that.
