### ISSUE TITLE
Update for roave/better-reflection ?

### ISSUE THREAD

**Issue by sigzegv** [lvht/phpcd.vim#161]
On Archlinux php is running v7.3, and your included better-reflection v2.0.x only support lower php versions. Do you plan to upgrade to roave/better-reflection v3.2 which supports php up to v7.4 ?

I tried to force it manually to 3.2 on the composer.json (and I also changed php-parser to v4.1 ) and all seems to work as usual.

**Comment by lvht** [comment]
It seems no harm. I upgraded at https://github.com/lvht/phpcd.vim/commit/06146630399773c778250c2b7d5ec3886c6cd457. Please report any issue you account.
