### ISSUE TITLE
phpcd move cursor to split below instead of autocompleting 

### ISSUE THREAD

**Issue by allan-simon** [lvht/phpcd.vim#164]
I'm using master version (currently 061466303997)

if I have two "splits" opened (by using `:sp` ) and the cursor editing the split at the top with a code like this :  (| is where my cursor is , not an actual character in my code)
```
$user->|($password);
```

as soon as i put `i` to enter in edition mode,  my cursor now jumped to the split below (in edition mode, so now the text i'm typing is erronously written in the split below)

note that if i have no split below opened (having split opened on the left/top etc. does not produce the issue) the autocompletion works correctly 

if the code is something like that:
```
$user->set|($password);
```
same problem 

it looks similar to this https://github.com/lvht/phpcd.vim/pull/128  (except that there's no exception being thrown, my code has no syntax error in it)

**Comment by lvht** [comment]
may be not exists anymore, please try the latest master branch, if you still use phpcd.
