### ISSUE TITLE
How to use the FuzzyMatcher?

### ISSUE THREAD

**Issue by Slamdunk** [lvht/phpcd.vim#166]
Hi, I've seen the PrefixMatcher is hardcoded in PHPCD:

https://github.com/lvht/phpcd.vim/blob/f46b5da7140365eceda096e2e5dbf094489d00ac/php/PHPCD.php#L63

And even though there is a `setMatchType` method, it seems to me that there's no way to configure it without altering the phpcd.vim source code, i.e. with a variable, is it?

**Comment by lvht** [comment]
The fuzzy matcher is abandoned. Please use something like [deoplete.vim](https://github.com/Shougo/deoplete.nvim) instead.

**Comment by Slamdunk** [comment]
Hi, I'm already using deoplete, but it can't leverage the features of PHPCD Reflection, AFAIK deoplete can only work with tags out-of-the-box.

This is also the reason I opened https://github.com/lvht/phpcd.vim/pull/165:

![maiusc](https://user-images.githubusercontent.com/152236/50593188-9be77a80-0e97-11e9-98c8-3ea2484bffe1.png)

![minusc](https://user-images.githubusercontent.com/152236/50593191-9db13e00-0e97-11e9-9174-6844caae2b2d.png)

**Comment by lvht** [comment]
Have you run the `:UpdateRemotePlugins`?

**Comment by Slamdunk** [comment]
I'm using VIM 8.0.1766, `:UpdateRemotePlugins` only works on NeoVIM, doesn't it?

**Comment by lvht** [comment]
deoplete seems to be neovim only

**Comment by Slamdunk** [comment]
No it isn't, it works flawlessly on Vim 8, which ports async jobs in Vim too.
It is in the readme of Deoplete: `Deoplete is the abbreviation of "dark powered neo-completion". It provides an extensible and asynchronous completion framework for neovim/Vim8.`

**Comment by lvht** [comment]
phpcd offers https://github.com/lvht/phpcd.vim/blob/master/rplugin/python3/deoplete/sources/phpcd.py.

however, it seems breaks. So we need to adopt to the newer deoplete.
