### ISSUE TITLE
Add completion and goto for PHPDoc

### ISSUE THREAD

**Issue by Slamdunk** [lvht/phpcd.vim#167]
AFAIK, completion and goto don't work on PHPDoc, i.e. on `fooBarBaz`, do them?
```php
/**  
 * @see \Abc\Def:fooBarBaz()
 */
public function wut() {}
```
It would be nice to have them working there too

**Comment by lvht** [comment]
It seems the `@see` works out of box. You should use `::` to indicate method

```php
/**  
 * @see \Abc\Def::fooBarBaz()
 */
public function wut() {}
```
