### ISSUE TITLE
Open php file error in php5 branch

### ISSUE THREAD

**Issue by freefly801213** [lvht/phpcd.vim#172]
error message:

> PHP Fatal error:  Uncaught exception 'ErrorException' with message 'Argument 1 passed to PHPCD\Matcher\Factory::make() must be an instance of PHPCD\Matcher\string, string given, called in /Users/freedom/.
dotvim/vim/bundle/phpcd.vim/php/PHPCD.php on line 55 and defined' in /Users/freedom/.dotvim/vim/bundle/phpcd.vim/php/Matcher/Factory.php:10

> Stack trace:

> #0 /Users/freedom/.dotvim/vim/bundle/phpcd.vim/php/Matcher/Factory.php(10): {closure}(4096, 'Argument 1 pass...', '/Users/freedom/...', 10, Array)
#1 /Users/freedom/.dotvim/vim/bundle/phpcd.vim/php/PHPCD.php(55): PHPCD\Matcher\Factory::make('prefix')
#2 /Users/freedom/.dotvim/vim/bundle/phpcd.vim/php/main.php(38): PHPCD\PHPCD->__construct('/Users/freedom/...', Object(Monolog\Logger), '0')
#3 {main}

>   thrown in /Users/freedom/.dotvim/vim/bundle/phpcd.vim/php/Matcher/Factory.php on line 10
Fatal error: Uncaught exception 'ErrorException' with message 'Argument 1 passed to PHPCD\Matcher\Factory::make() must be an instance of PHPCD\Matcher\string, string given, called in /Users/freedom/.dotvi
m/vim/bundle/phpcd.vim/php/PHPCD.php on line 55 and defined' in /Users/freedom/.dotvim/vim/bundle/phpcd.vim/php/Matcher/Factory.php on line 10
ErrorException: Argument 1 passed to PHPCD\Matcher\Factory::make() must be an instance of PHPCD\Matcher\string, string given, called in /Users/freedom/.dotvim/vim/bundle/phpcd.vim/php/PHPCD.php on line 55
 and defined in /Users/freedom/.dotvim/vim/bundle/phpcd.vim/php/Matcher/Factory.php on line 10

> Call Stack:

> 0.0004     246384   1. {main}() /Users/freedom/.dotvim/vim/bundle/phpcd.vim/php/main.php:0
> 0.0101    1217024   2. PHPCD\PHPCD->__construct() /Users/freedom/.dotvim/vim/bundle/phpcd.vim/php/main.php:38
> 0.0102    1221336   3. PHPCD\Matcher\Factory::make() /Users/freedom/.dotvim/vim/bundle/phpcd.vim/php/PHPCD.php:55
> 0.0102    1222080   4. {closure:/Users/freedom/.dotvim/vim/bundle/phpcd.vim/php/main.php:4-6}() /Users/freedom/.dotvim/vim/bundle/phpcd.vim/php/PHPCD.php:10

**Comment by lvht** [comment]
The php5 branch is no longer maintained. Please consider upgrade to the master branch.
