### ISSUE TITLE
Error detected while processing function phpcd#JumpToDefinition[10]..phpcd#LocateSymbol

### ISSUE THREAD

**Issue by richardeaxon** [lvht/phpcd.vim#175]
If I try to jump using Ctrl-] to any local scope variable like $result in a class'es method I get the below stack trace. 

Jumping to $this->variable works fine, jumping to a method definition works fine as does jumping to a namespace. I just have issues jumping to a local variable definition.

Using vim 8.0.1806 and php 7.1.17

Any help would be appreciated. Thanks.

Error detected while processing function phpcd#JumpToDefinition[10]..phpcd#LocateSymbol:
line   52:
E714: List required
line   55:
E121: Undefined variable: path
E15: Invalid expression: [path, line, 0]
Error detected while processing function phpcd#JumpToDefinition:
line   10:
E714: List required
line   11:
E121: Undefined variable: symbol_file
E15: Invalid expression: symbol_file == '' || symbol_file == v:false
line   30:
E121: Undefined variable: symbol_line
E116: Invalid arguments for function str2nr(symbol_line) > 0
PHP  14. include() /root/.vim/bundle/phpcd.vim/vendor/composer/ClassLoader.php:444

**Comment by lvht** [comment]
![image](https://user-images.githubusercontent.com/2030591/59743054-bb395f00-92a1-11e9-9d1a-8ec396eb94c7.png)
when i type ctrl + ], does not show any error.

**Comment by richardeaxon** [comment]
Thanks for the quick response. Your example gives me the same stack trace.

Error detected while processing function phpcd#JumpToDefinition[10]..phpcd#LocateSymbol:
line   52:
E714: List required
line   55:
E121: Undefined variable: path
E15: Invalid expression: [path, line, 0]
Error detected while processing function phpcd#JumpToDefinition:
line   10:
E714: List required
line   11:
E121: Undefined variable: symbol_file
E15: Invalid expression: symbol_file == '' || symbol_file == v:false
line   30:
E121: Undefined variable: symbol_line
E116: Invalid arguments for function str2nr(symbol_line) > 0
PHP  14. include() /root/.vim/bundle/phpcd.vim/vendor/composer/ClassLoader.php:444
