### ISSUE TITLE
php7.4兼容问题

### ISSUE THREAD

**Issue by yawepe** [lvht/phpcd.vim#179]
![image](https://user-images.githubusercontent.com/3320978/69896376-ce387b00-1379-11ea-85ee-e7ea1f81fe45.png)
![image](https://user-images.githubusercontent.com/3320978/69896387-eb6d4980-1379-11ea-85c1-dfeffc06df2b.png)

**Comment by lvht** [comment]
fixed by https://github.com/lvht/phpcd.vim/commit/0f56ec88fd419cbd772e9052a60e8c376a766442
