### ISSUE TITLE
Error when Jump to definition

### ISSUE THREAD

**Issue by minhchu** [lvht/phpcd.vim#184]
<img width="1050" alt="Screen Shot 2020-08-27 at 18 23 27" src="https://user-images.githubusercontent.com/14136809/91437119-8f493e80-e893-11ea-8a9f-2526fec47177.png">

Nvim: 0.4.4
OS: MacOs Catalina 10.15.6
PHP: 7.3 (default)

**Comment by lvht** [comment]
please make sure your nvim has started phpcd process successfully.

**Comment by minhchu** [comment]
How can I check 🤔

**Comment by lvht** [comment]
phpcd is a hack util for php developers who are familiar with vim and willing to make time to dig how it works.

if you do not want to how phpcd works, then phpcd will not help you too much, and you should choose some ide like phpstom.

Please do not make issue for asking how can i check. Just read the viml and php code. If you do not understand some port of the code, feel free to ask any question.

**Comment by minhchu** [comment]
It seems that the issue is `php-msgpack` is missing. So the rpc request from vim to php code is false.
Install new `php 7.4` with `mgspack` fix the issue

**Comment by lvht** [comment]
> It seems that the issue is php-msgpack is missing. So the rpc request from vim to php code is false.
Install new php 7.4 with mgspack fix the issue

👍 @minhchu
