### ISSUE TITLE
There appears to be no way to 'reload the index' when the path changes.

### ISSUE THREAD

**Issue by FlickerBean** [lvht/phpcd.vim#188]
I use a plugin called tcd, which allows each tab to have a different project in it by doing a `cd` to each projects directory when the tab changes.

This is obscure I realise but there appears to be no way to force phpcd.vim to 'reload the index'.

I've try `let phpcd_root=//new path` And various other things such as setting need_update and calling various Index() functions. But regardless of what I do, I'm unable to force it to update when switching tabs.

As a result, I end up with the autocomplete results from whatever the first project opened was, regardless of the project i'm currently working on.

Do you have any hints as to how I can work around this and force phpcd.vim to switch to the new project when I open a file from another project/root dir?

**Comment by lvht** [comment]
You can add the following line to your vimrc. 
```
let let:phpcd_auto_restart = 1
```

However, this will restart phpcd daemon every time you switch buffer. It maybe slow your vim.
I recommend to open different vim instances for different project.

**Comment by FlickerBean** [comment]
Thanks! This is really useful.

Is there not a command I can call to force a restart myself though? An autocommand on tabswitch would be ideal in my personal situation.

Having multiple vims open per project would go against the way I've used vim for the last 10+ years!

**Comment by lvht** [comment]
If not set the `g:phpcd_auto_restart`, you could run `:call phpcd#OpenFileNoAutoRestart()` after tap switch.
