### ISSUE TITLE
多个->调用分行时无法定位函数定义位置

### ISSUE THREAD

**Issue by imaben** [lvht/phpcd.vim#2]
例如
$this->message_service->getMessage();
当光标放在getMessage上时，按Ctrl+]是可以定位的函数位置的，但是如果调用时分行，例如：
$this->message_service
        ->getMessage();
这种情况就无法再定位getMessage函数位置了！

**Comment by lvht** [comment]
@imaben 搞定了，参见 ceb14820273bfa8966138dbccd4644252957baaa
