### ISSUE TITLE
BetterReflection to avoid loading classes?

### ISSUE THREAD

**Issue by Xerkus** [lvht/phpcd.vim#24]
Can you take a look at [BetterReflection](https://github.com/Roave/BetterReflection)?
May be it will be possible to avoid actually loading classes or may be more options to expand phpcd functionality.

**Comment by lvht** [comment]
fixed by https://github.com/lvht/phpcd.vim/commit/4554d76e45e856204ca06a42a6946035d2575d43

And more refactor based on better reflection will coming soon.

**Comment by lvht** [comment]
better reflection is no so better... reverted.

**Comment by lvht** [comment]
Use better-reflection to get information of current file without autoload enabled. Please see https://github.com/lvht/phpcd.vim/compare/0fac411752768388c4296066c020054439648a97...lvht:master
