### ISSUE TITLE
namespace autocompletion

### ISSUE THREAD

**Issue by Xerkus** [lvht/phpcd.vim#28]
Is it possible to add namespace autocompletion as well? We already have list of all defined classes, thanks to composer classmap.
I would like to also have autocompletion for use and namespace statements.

**Comment by sserbin** [comment]
Thanks, @lvht 

There's one thing the completion doesn't cover though - if you are in a namespaced file, like the following and you have  `Foo\Bar` class already defined:
```
<?php
namespace Foo;
use Ba<>;
```
the completion won't work here as `Bar` is not a FQCN.
It would work, however, with `use Foo\Ba<>`

**Comment by lvht** [comment]
This feature is implemented very simple. First, you need run `composer dump-autoload -o`. And composer will dump all classname to `vendor/composer/autoload_classmap.php`. And when you type `use Bar<>`, phpcd will load the `autoload_classmap.php` and pop the menu.

**Comment by sserbin** [comment]
@lvht 
> And when you type use Bar<>, phpcd will load the autoload_classmap.php and pop the menu.

It'd attempt to, that's correct - but you wouldn't get any completion list in the case above (you are in a namespaced file trying to complete sub-namespace). In this case, the `$pattern` in `classmap` function would be equal to `Ba` which wouldn't match against the classmap entry `Foo\\Bar`

Hope that makes sense.
