### ISSUE TITLE
当前文件有语法错误的时候整个vim会卡死

### ISSUE THREAD

**Issue by imaben** [lvht/phpcd.vim#3]
如题，建议先用php -l命令检查一下当前文件的PHP语法，没问题再执行后面的操作！如果可以，把错误的行号匹配出来，使错误行高亮，这样就完美了！

**Comment by lvht** [comment]
@imaben 事先检查 PHP 语法确实是个好办法

**Comment by lvht** [comment]
@imaben 按照你的思路修复了，参考 2c82e149c41f49a4646360b282550cc2cea68391
