### ISSUE TITLE
Channel error using vim 8

### ISSUE THREAD

**Issue by shadowhand** [lvht/phpcd.vim#53]
The first completion after opening a new file always seems to work. Repeating the same completion, or any other completion, then fails with this message:

```
Error detected while processing function phpcd#CompletePHP[54]..phpcd#GetCurrentNameSpace[1]..rpc#request:
line    6:
E906: not an open channel
```

Running `ps aux | grep php` shows that there are two PHPCD processes running:

```
wgilk           42770   0.0  0.1  2489520  11080   ??  Ss    8:34PM   0:00.02 /usr/local/bin/php /Users/wgilk/.vim/plugged/phpcd.vim/php/main.php /Volumes/Webserver/league/oauth2-google PHPID json
wgilk           42769   0.0  0.1  2479280  11188   ??  Ss    8:34PM   0:00.02 /usr/local/bin/php /Users/wgilk/.vim/plugged/phpcd.vim/php/main.php /Volumes/Webserver/league/oauth2-google PHPCD json
```

Sometimes the complete will start working again after some period of time, and sometimes it does not.

**Comment by lvht** [comment]
Have you added the `autocmd FileType php setlocal omnifunc=phpcd#CompletePHP` to your vimrc?

**Comment by shadowhand** [comment]
Yes:

```vim
" Enable phpcd omnicomplete
autocmd FileType php setlocal omnifunc=phpcd#CompletePHP
```

**Comment by lvht** [comment]
I cannot reoccur this problem.

**Comment by lvht** [comment]
Is there any output in `~/.phpcd.log`?

**Comment by shadowhand** [comment]
That file doesn't exist on my machine. I have this problem with all PHP versions: 5.6, 7.0, 7.1.

**Comment by stepiiik** [comment]
Same error on my machine. But only on MacVim. Vim in iTerm2 do it without problems.

I tried to find more about this error and I found only that problem is double running of GetCurrentNameSpace with same classname. It looks like RPC call returns nothing second time.

**Comment by lvht** [comment]
@stepiiik which version of vim does your MacVim used ?

**Comment by stepiiik** [comment]
@lvht it's this build https://github.com/macvim-dev/macvim/releases/tag/snapshot-114

**Comment by v-leonhou** [comment]
i meet the same error when i just typed Ctr+c ,then the message occured like this
![qq 20170204111653](https://cloud.githubusercontent.com/assets/8463045/22615225/77d54b50-eacb-11e6-82ea-f789621e6d1e.png)

**Comment by wsdjeg** [comment]
@lvht I get same issue as @v-leonhou shown above.

**Comment by lvht** [comment]
@v-leonhou @wsdjeg this error means you phpcd has not started successfully. If you phpcd started, you will see

![image](https://cloud.githubusercontent.com/assets/2030591/22649449/e9e94fe8-ecb5-11e6-93ee-d59d182f7730.png)

**Comment by wsdjeg** [comment]
but all the requirements I have installed, btw, is there any command I can test for it?
```
✔ wsdjeg:SpaceVim [ dev | ✔  ] ➭ php -m | grep js
json
✔ wsdjeg:SpaceVim [ dev | ✔  ] ➭ php -m | grep ^m
mbstring
msgpack
mysqlnd
✔ wsdjeg:SpaceVim [ dev | ✔  ] ➭ 
```

**Comment by lvht** [comment]
@v-leonhou please go to the `phpcd.vim` and run `composer install`

**Comment by v-leonhou** [comment]
i have got that ,anyway,thanks @lvht @wsdjeg

**Comment by shadowhand** [comment]
Why was this closed? I still get this error all the time.

**Comment by v-leonhou** [comment]
@shadowhand  go to the phpcd.vim and run composer install

**Comment by shadowhand** [comment]
@v-leonhou I just did that, I am currently on `master`, rev 132ef9564a726a5e3d75aae99edd9b77834f71f2. Ran `composer install`, fully updated. Restarted vim. First time I used `namespace` complete, everything was fine. Second time:

<img width="835" alt="screenshot 2017-03-08 19 48 29" src="https://cloud.githubusercontent.com/assets/38203/23732390/6ca342b0-0438-11e7-841c-30433a1e1994.png">

**Comment by shadowhand** [comment]
Looking closer, the error is different. Instead of saying

> E906: not an open channel

We now have:

> E714: List required

**Comment by lvht** [comment]
@shadowhand please offer the php code to reoccur this issue. thanks.

**Comment by shadowhand** [comment]
It happens on any PHP codebase when:

1. Open any PHP file, type `namespace X` where X is the first letter of a namespace, use TAB or whatever character is bound to completion to complete the namespace
2. Open another PHP file in a new tab, repeat the same steps
3. The error will be triggered

Note that this appears to only happen under MacVim, not vim proper.

**Comment by shadowhand** [comment]
There is no additional info in `~/.phpcd.log`.

**Comment by lvht** [comment]
@shadowhand it seems to be an MacVim's issue. Look at the below screen short, the upper is MacVim and the other is vim under iTerm2. When you use TAP to try to complete namespace, vim will send `[0, 1, 'psr4ns', ['/Users/lvht/a.php']]` to phpcd.php process, and phpcd.php will response like `[1,1,null,[]]`. However, MacVim cannot always be able to get this response, and then the error raised.

![image](https://cloud.githubusercontent.com/assets/2030591/23741742/01dc0bb2-04e5-11e7-89a3-0f5dcef97920.png)

**Comment by adelowo** [comment]
I had this problem on Neovim (minutes ago), all I had to was `sudo apt install php-msgpack`... I found this out via monitoring `~/phpcd.log` (`tail -f ~/phpcd.log`)..

Might help someone
