### ISSUE TITLE
Unknown function: job_start 报错是什么情况？

### ISSUE THREAD

**Issue by chenwenzhang** [lvht/phpcd.vim#56]
我是用vundle安装的。
打开php文件的时候报错，错误信息如下：
Error detected while processing function rpc#start:
line    6:
E117: Unknown function: job_start
E15: Invalid expression: job_start(args, {'out_cb': function('s:OnCall')})
E117: Unknown function: job_start
E15: Invalid expression: job_start(args, {'out_cb': function('s:OnCall')})

**Comment by lvht** [comment]
job_start 是 vim 7.4 以后引入的新功能。

![image](https://cloud.githubusercontent.com/assets/2030591/19228019/7fed6522-8ef3-11e6-891a-20022c10e98d.png)

**Comment by chenwenzhang** [comment]
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Sep 20 2016 21:15:50)
我的版本是7.4的 好像没有这个功能，看来要升级一下，谢谢楼主这么快回复

**Comment by chenwenzhang** [comment]
@lvht  我用homebrew安装的vim为什么还是7.4的，你截图显示你安装的是8.0的，为什么啊？

**Comment by lvht** [comment]
`brew update`?

**Comment by pcworld** [comment]
README currently claims:
> NeoVim and Vim 7.4+ are supported now

I assume this should be changed?

**Comment by lvht** [comment]
@pcworld change to what?

**Comment by pcworld** [comment]
@lvht This issue sounds like only vim 8.0+ is compatible with this plugin. Or can one compile vim 7.4 with "jobs" support?

**Comment by lvht** [comment]
jobs was introduced in vim7.4+. so phpcd support both vim7.4 and vim8
