### ISSUE TITLE
Jump to file

### ISSUE THREAD

**Issue by jrean** [lvht/phpcd.vim#64]
Hi,

Is there a way you could implement a "jump to file" and so avoid to manipulate the annoying `vim path`...?

Thank you for your fantastic package.

**Comment by lvht** [comment]
I can not get you idea. What does the "jump to file" means?

**Comment by jrean** [comment]
Jumping to file with `gf` (go to file).
I use the vim `path`. For each of my project I set a "local" `vimrc` file where I define the path(s) where I want to vim to search...

I was wondering if you could implement something based on the `autoload` file and so leverage the power of composer. It's like the go to definition but for file(s).

**Comment by lvht** [comment]
if you include php file by
```<?php
include __DIR__ . '/path/to/a.php';
```
you can move cursor to path string and press C-] to go to a.php.
