### ISSUE TITLE
Opening a new PHP file kills current vim jobs. 

### ISSUE THREAD

**Issue by przepompownia** [lvht/phpcd.vim#73]
What is the reason to [kill jobs every time](https://github.com/lvht/phpcd.vim/blob/master/ftplugin/php_phpcd.vim#L31
) when opening a new PHP file and start the new instances? It takes unnecessary time.

[Changes in my fork](https://github.com/przepompownia/phpcd.vim/commit/a99b372c8b5b4a703058864a85e733e0bdb478c1) seems to work without any problem.

**Comment by lvht** [comment]
This was introduced by 85bdebb0fc5ed970a31f6306bc22a444abeb0f7a . When you change from one php project to another, phpcd.vim will auto restart. However, this feature has been break up. And I fixed it by 75c8023e78ecfe22638cf84ebbc22546be1a0bb0 .
