### ISSUE TITLE
No constant completion

### ISSUE THREAD

**Issue by sserbin** [lvht/phpcd.vim#78]
Test case 1:
```php
<?php
class foo {
    const bar = 42;
}
foo::<tab>
```
_Expected:_ `bar` appears in omni-completion choices.
_Actual:_ no choices

Test case 2:
```php
<?php
class foo {
    const bar = 42;
    public function baz() {
        self::<tab>
    }
}
``` 

Edit: phpcd version: master; php - PHP 7.1.2-4+deb.sury.org~xenial+1

**Comment by lvht** [comment]
please ensure that you can make an instance of class **foo** without include its source php file.
