### ISSUE TITLE
method declarations missing typehints of params and return typehints

### ISSUE THREAD

**Issue by nclundsten** [lvht/phpcd.vim#80]
```
/**
 * @param \StdClass $a
 * @return void
 */
public function myMethod(\StdClass $a)  : void
{ 
}

```
results in 

> \+ myMethod (a)    _f_ 

which is not very useful, would expect something like:

> \+ myMethod (\StdClass $a) : void    _f_

is there a way to configure this, or is it really limited to just the parameter names?

**Comment by lvht** [comment]
Hello, @nclundsten as phpcd.vim is mainly a php script, you can make your try to make phpcd.vim better :) 

The item info of the completion list is generated at [this function](https://github.com/lvht/phpcd.vim/blob/master/php/PHPCD.php#L737). In the `getMethodInfo` function, the first parameter is a instance of [`ReflectionMethod`](http://php.net/manual/en/class.reflectionmethod.php), and it has a `getReturnType` method. This method is only available for php 7.x.

**Comment by wsdjeg** [comment]
I will look in to it.

**Comment by nclundsten** [comment]
I've found a good alternative to cluttering the candidates list:

https://github.com/nclundsten/phpcd.vim/commit/809efc4fc582a12bc5bcd9941ecfd06d30f927f2

todo: php5.3 bc

I'll add a PR once finished.
