### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by codeinabox** [lvht/phpcd.vim#84]
When using this with Deoplete I get the following error

> [deoplete] Traceback (most recent call last):
> [deoplete]   File "/Users/matt/dotfiles/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 184, in merge_results
> [deoplete]     context['candidates'] = f.filter(context)
> [deoplete]   File "/Users/matt/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/filter/matcher_full_fuzzy.py", line 26, in filter
> [deoplete]     return [x for x in context['candidates']
> [deoplete] TypeError: 'int' object is not iterable
> [deoplete] Could not filter using: <deoplete.filter.matcher_full_fuzzy.Filter object at 0x1021a2048>.  Use :messages for error details.

**Comment by lvht** [comment]
This error means that phpcd returns a int instead of a list to deoplete. Please offer more detail to recur this problem. Thanks.

**Comment by bfgasparin** [comment]
Same problem.

My deoplete config:

```
let g:deoplete#enable_at_startup = 1     
let g:deoplete#enable_smart_case = 0    
let g:deoplete#complete_method = 'complete'
let g:deoplete#omni_patterns = get(g:,'deoplete#omni_patterns',{})
let g:deoplete#omni_patterns.php = '->\|::'       
let g:deoplete#ignore_sources = get(g:, 'deoplete#ignore_sources', {})
let g:deoplete#ignore_sources.php = ['omni'] 
call deoplete#custom#set('phpcd', 'mark', '') 
let g:deoplete#disable_auto_complete = 0
```

I m currently using Ubuntu 16.04, with php 7.1 with `pcntl`, `json` and `msgpack` extension.

The same config works fine my Mac OS X.

**Comment by bfgasparin** [comment]
I changed the deoplete config to 

```
let g:deoplete#ignore_sources.php = ['phpcd', 'omni']
```

and everything worked fine.

**Comment by lvht** [comment]
Hello @bfgasparin . Thanks for your patience.  But please offer the php code in which this problem occurs.

**Comment by codeinabox** [comment]
Even a very simple PHP file causes this error for me eg

```php
<?php

$hello
```

The moment I start typing `$hello` the errors appeared but before that it was auto-completing PHP functions fine.

**Comment by lvht** [comment]
@codeinabox please update to the laste master codebase, and offer the content of `~/.phpcd.log`.

**Comment by codeinabox** [comment]
I deleted the existing log file and induced the error but it doesn't seem to create a new log file.

**Comment by codeinabox** [comment]
I no longer have this issue, thanks for the help
