### ISSUE TITLE
autocomplete not working: Class 'MessagePackUnpacker' not found

### ISSUE THREAD

**Issue by still-dreaming-1** [lvht/phpcd.vim#86]
I tried using this plugin a few times in the past, but it did not work very well for me. I suspect it was because our PHP code was very strange and stupid. Now that our code is a little more standard, I am giving this another try.

NVIM 0.1.7
PHP 7.1

I was getting errors with Deoplete, so I tried completely disabling Deoplete for now and just using Ctrl-x Ctrl-o to activate autocomplete. When I do that, I get the following error: 

> Error detected while processing function 
> phpcd#CompletePHP[54]..phpcd#GetCurrentNameSpace[1]..rpc#request:
> line       2:
> Invalid channel "4"

That is a little strange as I thought channels were used in Vim not Neovim.

Here are the contents of `~/.phpcd.log`:

> [05-Jul-2017 15:26:08 UTC] PHP Fatal error:  Uncaught Error: Class 'MessagePackUnpacker' not found in /home/jesse/.config/nvim/plugged/phpcd.vim/vendor/lvht/msgpack-rpc/src/MsgpackMessenger.php:18
> Stack trace:
> #0 /home/jesse/.config/nvim/plugged/phpcd.vim/php/main.php(27): Lvht\MsgpackRpc\MsgpackMessenger->__construct(Object(Lvht\MsgpackRpc\StdIo))
> #1 {main}
>    thrown in /home/jesse/.config/nvim/plugged/phpcd.vim/vendor/lvht/msgpack-rpc/src/MsgpackMessenger.php on line 18

I did a search in the PHP code under `/home/jesse/.config/nvim/plugged/phpcd.vim/` and there is no MessagePackUnpacker class defined anywhere even though I did run `composer install` from that directory.

**Comment by still-dreaming-1** [comment]
I guess the first question to figure out is where is the MessagePackUnpacker class supposed to be / come from?

**Comment by lvht** [comment]
https://github.com/msgpack/msgpack-php

**Comment by still-dreaming-1** [comment]
Thanks! I got it installed with `sudo pecl install msgpack` and then enabling it in the CLI php ini file.

**Comment by BH1SCW** [comment]
another solution:
sudo apt-get install php-msgpack
it works then:)
