### ISSUE TITLE
How to solve this?

### ISSUE THREAD

**Issue by asterism612** [lvht/phpcd.vim#87]
Error detected while processing function <SNR>98_OnCall:
line    2:
E701: Invalid type for len()
line    1:
E474: Invalid argument
line    2:
E701: Invalid type for len()
line    1:
E474: Invalid argument
line    2:
E701: Invalid type for len()
line    1:
E474: Invalid argument
line    2:
E701: Invalid type for len()
line    1:
E474: Invalid argument
line    2:
E701: Invalid type for len()
line    1:
E474: Invalid argument
line    2:
E701: Invalid type for len()
line    1:
E474: Invalid argument
line    2:
E701: Invalid type for len()
E701: Invalid type for len()
line    1:
E474: Invalid argument
line    2:
E701: Invalid type for len()
Press ENTER or type command to continue

**Comment by miguelbacalhau** [comment]
Not enough information.
When I used deoplete I think that is what happens when there is an error with phpcd.
Try using c-X c-O and see what happens

**Comment by chenping684** [comment]
估计是autoload设置不对,. 我也出现过这个问题,  原因是项目目录目录更改 ,  然后composer.json未更新(我仅仅用composer用来自动补全), 此时打开或者<c-w>w 会报 和 asterism612 一样的问题,   ctrl+] 则是其他报错信息

**Comment by Nomad145** [comment]
@asterism612, I have this problem a lot, too.  Looking at my `~/.phpcd.log` I noticed fatal errors coming from PHP.

```
[26-Sep-2017 22:26:24 UTC] PHP Fatal error:  Class TestClass contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (TestInterface::avg, TestInterface::max) in /Users/nomad/Code/engine/src/TestClass.php on line 11
```

I had just implemented an interface and hadn't yet defined the methods.  I'm assuming this happens if `phpcd` encounters any sort of exception/error when loading the working file (syntax errors, parse errors, etc).

**Comment by lvht** [comment]
syntax error and parse error can be catched by Error throwable. However, defining a class without implementing all methods is a true fatal error and cannot be handled by php code.
