### ISSUE TITLE
Index is not updated until Vim is reopened

### ISSUE THREAD

**Issue by rosmanov** [lvht/phpcd.vim#89]
Modifications to the existing classes do not take effect until Vim is reopened. Calling `phpcd#UpdateIndex()`, or even `phpcd#Index()` does not help, and there is nothing registered in the log (`~/.phpcd.log`).

# Steps to reproduce

1. Create a test project with the following structure:
```
phpcd-test/     
|-- composer.json
|-- src/
|   `-- Test.php
|-- test.php
`-- vendor/
    |-- autoload.php
```
**`composer.json`**
```
{
   ...
    "autoload": {
        "psr-4": {
            "Acme\\": "src/"
        }
    }
}
```
**`src/Test.php`**
```
<?php
namespace Acme;

class Test
{
    public function testA()
    {
    }
}
```
**`test.php`**
```
<?php
require 'vendor/autoload.php';

$obj = new Acme\Test;
```

2. Open `test.php`:
```
$ vim test.php
```
3. Go to the declaration of `Acme\Test` (<key>Ctrl</key>-<key>]</key>) class and add a public `testB` method:
```
    public function testB()
    {
    }
```
4. Return to `test.php` (<key>Ctrl</key>-<key>t</key>) and run the following Vim commands:
```
:call phpcd#UpdateIndex()
:call phpcd#Index()
```
5. At the bottom of the file write `$obj->`  and invoke <key>Ctrl</key>-<key>x</key>-<key>o</key>

# Expected Result

Popup menu with `testA` and `testB` methods.

# Actual Result

`testB` method is not suggested.

**Comment by lvht** [comment]
I cannot recur this  problem. Please offer more information.

BTW,  phpcd#UpdateIndex and phpcd#Index does not have any effect to completion.

**Comment by rosmanov** [comment]
@lvht Simply add a method, property, or something to an existing class. Then try to call it from another file using PHPCD: `$object->` (press `C-x C-o`). PHPCD offers only the old members. However, if you restart Vim, the new members will be there

**Comment by rosmanov** [comment]
> BTW, phpcd#UpdateIndex and phpcd#Index does not have any effect to completion.

Then I would like to have a function to actually update the index (completion info)

**Comment by lvht** [comment]
There is no need to update index. Because phpcd just use the Reflection to fetch completion information. And phpcd will restart everytime you press C-x C-o, so it will see the new method.

**Comment by lvht** [comment]
phpcd#UpdateIndex is only used for tracing interface's implemention. If we move cursor to an interface's method and press C-], phpcd will use these index to show a jump list.

**Comment by rosmanov** [comment]
Okay, here is all you need to reproduce the issue:
- `~/.vim`: [home-vim.zip](https://github.com/lvht/phpcd.vim/files/1144124/home-vim.zip)
- The test project: [phpcd-test.zip](https://github.com/lvht/phpcd.vim/files/1144126/phpcd-test.zip)

**Steps**
1. Download `home-vim.zip` into the `$HOME` directory and extract its contents:
```sh
mv ~/.vim ~/.vim-backup
mv ~/.vimrc ~/.vimrc-backup
cd ~
unzip home-vim.zip
```
2. Download the test project and extract it somewhere:
```sh
unzip phpcd-test.zip
cd phpcd-test
```
3. Open `test.php`:
```sh
vim test.php
```
4. Move cursor on `Acme\Test` and press `C-]`. PHPCD should open `phpcd-test/src/Test.php`
5. Add the following method to the `Acme\Test` class:
```php
    public function testC()
    {
    }
```
6. Save the file: `:w`, `Enter`
7. Press `C-t`. Vim should return you back to `test.php`.
8. After the declaration of `$obj` variable:
```php
$obj = new Acme\Test;
```
add the following:
```php
$obj->
```
9. Press `C-x`, then `C-o`

**Actual result**

![screenshot_2017-07-13_10-34-32](https://user-images.githubusercontent.com/608192/28151892-ebc12d96-67b6-11e7-9957-1caad292c144.png)

**Expected result**

If you quit without saving (`:q!`), open `test.php` file again, and invoke the completion for `$obj` again, the `testC` method will be there:
![expected](https://user-images.githubusercontent.com/608192/28151908-053c5b60-67b7-11e7-90cb-a29c5365160f.png)

**Comment by lvht** [comment]
Thank you for your patience and sorry for trouble. I will test you test project tonight (+8 zone).

**Comment by lvht** [comment]
@rosmanov please my test
[![asciicast](https://asciinema.org/a/im5LlBgUU0pwmjxBX6tJoUsUN.png)](https://asciinema.org/a/im5LlBgUU0pwmjxBX6tJoUsUN)

**Comment by rosmanov** [comment]
@lvht [![asciicast](https://asciinema.org/a/IyXtSywt72R7wT52xcMslE5YB.png)](https://asciinema.org/a/IyXtSywt72R7wT52xcMslE5YB)

**Comment by lvht** [comment]
Do you save the Test.php file after you add testC method?

**Comment by lvht** [comment]
@rosmanov I use vim to test your example, but cannot see your issue.

[![asciicast](https://asciinema.org/a/Fd0EtG4GHJ0q2Es6WnLzIbW1q.png)](https://asciinema.org/a/Fd0EtG4GHJ0q2Es6WnLzIbW1q)

**Comment by lvht** [comment]
I have no idea about your issue. It should not happen. Because fetch the object method completion list is nothing but like this
```php
<?php
$r = new ReflectionClass('Test');
$methods = $r-> getMethods();
```
And phpcd will fork a new process for each list fetch. And if you changed test.php, and saved it, the new process will see it's new method.

**Comment by rosmanov** [comment]
@lvht Yes, I save `Test.php` with `:w` command before pressing `C-t`. I even tried to save it multiple times and waiting for some time before trying to invoke the completion.

**Comment by lvht** [comment]
do you enable anything like opcache?

**Comment by rosmanov** [comment]
@lvht yes, I have opcache enabled. PHP 7.1

**Comment by lvht** [comment]
please disable opcache and try again.

**Comment by rosmanov** [comment]
@lvht without opcache, it works _as expected_

**Comment by rosmanov** [comment]
@lvht so PHPCD doesn't support Opcache? I would mention that in the docs then.

**Comment by lvht** [comment]
Please google what problem the opcache solves.

**Comment by lvht** [comment]
you should not open you opcache in your development environment.

**Comment by rosmanov** [comment]
@lvht I know the purpose of opcache extension, dude. The problem is that PHPCD doesn't work properly when this extension is enabled

**Comment by lvht** [comment]
@rosmanov you use opcache, you should know its features. With a not well configured opcache, even you php-fpm could not see you lastest change. Does php-fpm should mention it doesn't work properly with opcache?

**Comment by rosmanov** [comment]
@lvht, I suppose you are launching PHP CLI process for each `vim` instance. The problem is that the reflection data is cached until either the PHP process is replaced with a new one (with the up to date reflection info), or the contents of the opcode cache is invalidated with `opcache_reset()`, or the appropriate `opcache_invalidate()` function calls. One wayt

**Comment by lvht** [comment]
http://php.net/manual/en/opcache.configuration.php#ini.opcache.revalidate-freq

**Comment by lvht** [comment]
and http://php.net/manual/en/opcache.configuration.php#ini.opcache.save-comments

**Comment by rosmanov** [comment]
@lvht You could handle the issue in your PHP process. At least I have given you advice.

Please yourself.
