### ISSUE TITLE
Overriding property type in derived class

### ISSUE THREAD

**Issue by rosmanov** [lvht/phpcd.vim#90]
Consider the following classes:
```php
class Base
{
    /**
     * @var BaseType
     */
    protected $prop;
}
class Child extends Base {}
```
How do I set a type for `$prop` property in the `Child` class using annotations?

`/** @var AnotherType $prop */` doesn't work unless I copy the property declaration into the child class.

**Comment by miguelbacalhau** [comment]
use {@inheritDoc}

**Comment by rosmanov** [comment]
@miguelbacalhau how, exactly?

**Comment by miguelbacalhau** [comment]
Looking at it now I am not sure what a I said is correct.

I know you can use `/**  {@inhritdoc} */ with methods but for properties I am not sure.
