### ISSUE TITLE
Unable to use it

### ISSUE THREAD

**Issue by vivoconunxino** [lvht/phpcd.vim#91]
I've got an error when I hit C-x C-o:

Error detected while processing function 

> phpcd#CompletePHP[54]..phpcd#GetCurrentNameSpace[1]..rpc#request:
> line    2:
> Invalid channel "3"

Using nvim + php7.1
I installed the msgpacker
I created a .phpcd.vim on the root of the project, redirecting to my codeigniter autoload (application/config/autolaod.php):

> let g:phpcd_autoload_path = 'application/config/autoload.php'
> let g:phpcd_php_cli_executable = 'php7.1'

The log doesn't report anything for this error.

**Comment by miguelbacalhau** [comment]
Maybe you are missing a dependency try to run the deamon from outside of vim.
I think if you create a .phpcd.vim you don't need the:
``` vim
let g:phpcd_autoload_path = 'application/config/autoload.php'
```

**Comment by vivoconunxino** [comment]
AFAIK the .phpcd.vim should contain the path to the autoload, so my .phpcd.vim contains:

> let g:phpcd_autoload_path = 'application/config/autoload.php'
> let g:phpcd_php_cli_executable = 'php7.1'

How can I execute the daemon manually?

**Comment by lvht** [comment]
try this
```bash
php ~/.config/nvim/plugged/phpcd.vim/php/main.php [path/to/project/root] msgpack [path/to/autoload/file]
```

**Comment by vivoconunxino** [comment]
Just to confirm that I'm happily using it with the suggested command

**Comment by vivoconunxino** [comment]
I've been playing with the plugin in order to know why was ignoring my composer autoload file and had to run the command manually...

The thing is, it worked fine with a Laravel project but didn't with a CodeIgniter one.

My composer wasn't loading all my classes (controllers, models, etc), in the vendor/composer/autoload_classmap.php. So I've tried to add them manually to my composer.json (autoload: {clasmap: [...]}). 

Now they seem included, my own folders (one for Domain/Entity, Domain/Repository) work perfectly with PHPCD, but the ones of the framework (models, controllers..) don't.

Would you suggest me any way to solve it please?

**Comment by lvht** [comment]
You need to implement the autoload function for CodeIgniter's models, controllers.. in your application/config/autoload.php
