### ISSUE TITLE
Auto-complete for language keywords

### ISSUE THREAD

**Issue by codeinabox** [lvht/phpcd.vim#93]
I noticed there is no auto-completion for `require` and `include`. Is this something that could be added? I am happy to raise a PR if someone can point me in the right direction.

**Comment by lvht** [comment]
auto-complete for require and include means complete for file path. You can try the deoplete.vim

**Comment by codeinabox** [comment]
Sorry I didn't mean completion of the file path, though that would be very handy, I meant if I start typing `req` then `require` doesn't show up in the completion list.
