### ISSUE TITLE
Definition navigation doesn't work for use statements

### ISSUE THREAD

**Issue by elazar** [lvht/phpcd.vim#94]
The definition navigation provided by this plugin works well for me in most contexts (e.g. parameter typehints, return types, annotations, etc.). However, one instance where it would be useful and doesn't appear to work is within `use` statements, e.g.

```
use Symfony\Component\Validator\Constraints;
```

**Comment by lvht** [comment]
`composer dump-autoload -o` will dump all class into `vendor/composer/autoload_classmap.php`.

**Comment by elazar** [comment]
@lvht That's not the issue. I can open `vendor/composer/autoload_classmap.php` and see the entry for the class I'm trying to load the declaration for. I am able to load the declaration for the same class from an annotation; I just can't load it from the `use` statement for that class.

**Comment by lvht** [comment]
maybe you need to get start at https://github.com/lvht/phpcd.vim/blob/master/autoload/phpcd.vim#L57-L59

**Comment by elazar** [comment]
@lvht Looks like that's our issue, yes. 😄 I'll try to create a PR soon if you don't do it first.

**Comment by lvht** [comment]
duplicate #28
