### ISSUE TITLE
Can't find our functions and constants

### ISSUE THREAD

**Issue by still-dreaming-1** [lvht/phpcd.vim#95]
I have a custom phpcd.vim at the project root directory. It sets the `g:phpcd_autoload_path` variable to point to a bootstratp file that ends up including the `/vendor/autoload.php` file as well as setting up other things that are required. The bootstrap file requires certain files that contain functions and constants we need. Even so, when I'm using phpcd, I keep getting errors that get logged about undefined variables and constants. These errors also cause deoplete to start complaining in a very disruptive way and then deoplete turns off phpcd support after too many errors.

**Comment by lvht** [comment]
You need use php to run the bootstrap file, and see the error.

**Comment by still-dreaming-1** [comment]
I figured out at least one case where this happens and I think phpcd itself could be improved. Sometimes I run into a strange situation where after I have used fugitive to compare a diff, I end up with only one window open, at it looks like a code file in my project, but it is actually some kind of git file or some file fugitive used to show me the old version of the code or something like that. So I make the mistake of thinking it is a file I want to edit, and I start editing the file. Then I get deoplete errors because phpcd doesn't understand what to do.

Anyway, I don't have a particularly technical suggestion because I don't fully understand the inner workings of phpcd and deoplete, but my suggestion is basically that phpcd should fail more gracefully and cooperate better with deoplete upon failure. If it can't work with something, it should not feed invalid data to deoplete, or whatever it is doing to trip up deoplete.

**Comment by still-dreaming-1** [comment]
I'm also certain in some situations my original problem is still real problem. There are no errors occuring in the bootstrap file and there are no errors in the file I am editing, yet phpcd cannot find our constants even though they have already been defined. In the case I am running into right now, it happens when I start typing out the method to call on an object. The class file it is from has constants at the very top of the file before the class is defined, but phpcd does not recognize them. I realize the way our code is organized goes against best practices, and we are working to clean it up, but I don't understand why using the bootstrap file is not making phpcd aware of these constants.

**Comment by lvht** [comment]
I made some change at ba943a9c46f20b6f1b061ca1fff62df36a5d9562 to fix deoplete verbose error.
