### ISSUE TITLE
spacevim don't work

### ISSUE THREAD

**Issue by lhyaax** [lvht/phpcd.vim#98]
I try this
`php ~/.cache/vimfiles/repos/github.com/php-vim/phpcd.vim/php/main.php /home/u/code/laravel  msgpack /home/u/code/laravel/vendor/autoload.php`
this had no return.

I use laravel framework.  
I try CTRL+]  on a function
spacevim warn 
`
[tag] Caching Done!
unite.vim] unite buffer "default" candidates are empty
`
what's wrong?

**Comment by lvht** [comment]
the tag warn means that you phpcd was not configured properly. please see the readme again.
